version: 0.2

phases:
  pre_build:
    commands:
      # Install AWS CLI
      - yum install -y awscli

  build:
    commands:
      # Modify the minimum size of Auto Scaling Group
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name myAutoScale --min-size 4
      - sleep 30
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name myAutoScale --min-size 2 --force-update
      - sleep 30
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name myAutoScale --max-size 2 --force-update
      - sleep 50
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name myAutoScale --max-size 4